### ISSUE TITLE
Person-tracking-deepsort-yolov5

### ISSUE THREAD

**Issue by TheMadScientiist** [pooya-mohammadi/today-i-learned#1]
Hello, thank you for your work in the community. There was a repository(Person-tracking-deepsort..." you created that I was using as a guide. Is there a way I can access this code? specifically the api app section. 

Thank you

**Comment by pooya-mohammadi** [comment]
@TheMadScientiist 
Hi, unfortunately, I cannot release that code in the near future. If you have any questions regarding your project, send me an email.

Email: pooyamohammadikazaj@gmail.com
best regards
